#!/usr/bin/env bash
# Builds the image, starts app + Nginx, sends multi-megabyte images through the proxy and checks that
# (1) Nginx wrote no request/response temp files for the app's routes, (2) the control route does trigger temp
# files (so the check works), (3) the app container is read-only, non-root, healthy and its filesystem unchanged.
set -euo pipefail
cd "$(dirname "$0")"
compose=(docker compose -f compose.yaml)
work="$(mktemp -d)"
cleanup() { "${compose[@]}" down -v --remove-orphans >/dev/null 2>&1 || true; rm -rf "$work"; }
trap cleanup EXIT

"${compose[@]}" up -d --build --wait >/dev/null

# A ~4 MB random-noise JPEG (no faces), generated by the app image itself and written to the host.
"${compose[@]}" run --rm --no-deps -T --entrypoint python app - > "$work/sample.jpg" <<'PY'
import io, sys
import numpy as np
from PIL import Image
pixels = np.random.default_rng(1).integers(0, 256, (1500, 2000, 3), dtype=np.uint8)
buf = io.BytesIO()
Image.fromarray(pixels).save(buf, format="JPEG", quality=95)
sys.stdout.buffer.write(buf.getvalue())
PY
size=$(wc -c < "$work/sample.jpg" | tr -d ' ')
echo "sample: $size bytes"
[ "$size" -gt 1048576 ] || { echo "FAIL: sample too small to exercise buffering"; exit 1; }

post() {  # path, extra header -> prints HTTP status and response size
  curl -sS -o "$work/out" -w "%{http_code} %{size_download}" -H "Content-Type: image/jpeg" ${2:+-H "$2"} \
    --data-binary @"$work/sample.jpg" "http://127.0.0.1:18080$1"
}
regions='X-Regions: [{"x":100,"y":100,"w":800,"h":600,"source":"manual"}]'

warnings() { "${compose[@]}" logs nginx 2>&1 | grep -c "buffered to a temporary file" || true; }

before=$(warnings)
echo "detect: $(post /api/detect)"
echo "blur:   $(post /api/blur "$regions")"
after=$(warnings)
temp_files=$("${compose[@]}" exec -T nginx sh -c 'find /var/cache/nginx -type f | wc -l' | tr -d ' ')
echo "nginx temp-file warnings for app routes: $((after - before)); files under /var/cache/nginx: $temp_files"
[ "$((after - before))" -eq 0 ] || { echo "FAIL: Nginx buffered app traffic to disk"; exit 1; }

echo "control detect: $(post /__control/api/detect)"
echo "control blur:   $(post /__control/api/blur "$regions")"
control=$(( $(warnings) - after ))
echo "nginx temp-file warnings for the control route: $control"
[ "$control" -ge 1 ] || { echo "FAIL: control route did not buffer to disk — the check cannot detect regressions"; exit 1; }

app_id=$("${compose[@]}" ps -q app)
readonly_fs=$(docker inspect -f '{{.HostConfig.ReadonlyRootfs}}' "$app_id")
user=$("${compose[@]}" exec -T app id -u | tr -d '\r')
health=$(docker inspect -f '{{.State.Health.Status}}' "$app_id")
changes=$(docker diff "$app_id" | wc -l | tr -d ' ')
echo "app: read-only=$readonly_fs uid=$user health=$health filesystem-changes=$changes"
[ "$readonly_fs" = true ] && [ "$user" = 10001 ] && [ "$health" = healthy ] && [ "$changes" = 0 ] \
  || { echo "FAIL: app container hardening"; exit 1; }

echo "PASS"
