#!/usr/bin/env bash
# Builds the image and runs it behind Nginx 1.24.0 with the production proxy snippet, then:
# (1) /api/detect and /api/blur must return 200 with a valid body (JSON of the right shape; a real JPEG of the
#     right size) over HTTP/1.1 and over HTTPS + HTTP/2;
# (2) Nginx must write no request/response temp files for the app's routes;
# (3) a control route with default-style buffering must produce temp files (so check 2 can detect a regression);
# (4) the validators must reject wrong answers (404, swapped bodies) — so check 1 can detect a broken API;
# (5) the app container must be read-only, non-root, healthy, with an unchanged filesystem.
set -euo pipefail
cd "$(dirname "$0")"
compose=(docker compose -f compose.yaml)
work="$(mktemp -d)"
cleanup() { "${compose[@]}" down -v --remove-orphans >/dev/null 2>&1 || true; rm -rf "$work"; }
trap cleanup EXIT
fail() { echo "FAIL: $*"; exit 1; }

mkdir "$work/certs"
openssl req -x509 -newkey rsa:2048 -nodes -days 1 -subj "/CN=localhost" \
  -keyout "$work/certs/privkey.pem" -out "$work/certs/fullchain.pem" >/dev/null 2>&1
chmod 644 "$work/certs/"*.pem
export SMOKE_CERT_DIR="$work/certs"

"${compose[@]}" up -d --build --wait >/dev/null

# A ~3.5 MB random-noise JPEG, 2000x1500 (no faces), generated by the app image and written to the host.
"${compose[@]}" exec -T app python - > "$work/sample.jpg" <<'PY'
import io, sys
import numpy as np
from PIL import Image
pixels = np.random.default_rng(1).integers(0, 256, (1500, 2000, 3), dtype=np.uint8)
buf = io.BytesIO()
Image.fromarray(pixels).save(buf, format="JPEG", quality=95)
sys.stdout.buffer.write(buf.getvalue())
PY
size=$(wc -c < "$work/sample.jpg" | tr -d ' ')
echo "sample: $size bytes"
[ "$size" -gt 1048576 ] || fail "sample too small to exercise buffering"

# validate KIND FILE: exit 0 only for a valid body. KIND = detect (JSON) or blur (JPEG image).
read -r -d '' VALIDATE <<'PY' || true
import io, json, sys
kind, data = sys.argv[1], sys.stdin.buffer.read()
W, H = 2000, 1500
try:
    if kind == "detect":
        body = json.loads(data)
        assert set(body) >= {"width", "height", "count", "faces"}, "keys"
        assert (body["width"], body["height"]) == (W, H), "size"
        assert isinstance(body["faces"], list) and body["count"] == len(body["faces"]), "count"
        for face in body["faces"]:
            assert all(isinstance(face[k], int) for k in ("x", "y", "w", "h")), "face"
    else:
        from PIL import Image
        with Image.open(io.BytesIO(data)) as img:
            assert img.format == "JPEG" and img.size == (W, H), "image"
            img.load()  # full decode: a truncated or corrupt JPEG raises here (verify() alone does not)
except Exception as error:
    print(f"invalid {kind} body: {error!r}", file=sys.stderr)
    sys.exit(1)
PY
validate() { "${compose[@]}" exec -T app python -c "$VALIDATE" "$1" < "$2"; }

# request NAME URL [extra curl args...] -> body in $work/NAME, "status http_version content_type" on stdout
request() {
  local name="$1" url="$2"; shift 2
  curl -sS -o "$work/$name" -w "%{http_code} %{http_version} %{content_type}" \
    -H "Content-Type: image/jpeg" --data-binary @"$work/sample.jpg" "$@" "$url"
}
# expect_ok NAME KIND STATUS_LINE [PROTOCOL]: status 200, valid body, and (if given) the HTTP version.
expect_ok() {
  local name="$1" kind="$2" line="$3" proto="${4:-}"
  read -r status version ctype <<<"$line"
  echo "$name: HTTP/$version $status $ctype $(wc -c < "$work/$name" | tr -d ' ') bytes"
  [ "$status" = 200 ] || fail "$name returned HTTP $status"
  [ -z "$proto" ] || [ "$version" = "$proto" ] || fail "$name used HTTP/$version, expected HTTP/$proto"
  validate "$kind" "$work/$name" || fail "$name body is not a valid $kind result"
}

regions='X-Regions: [{"x":100,"y":100,"w":800,"h":600,"source":"manual"}]'
warnings() { "${compose[@]}" logs nginx 2>&1 | grep -c "buffered to a temporary file" || true; }
before=$(warnings)

http=http://127.0.0.1:18080
https=https://localhost:18443
h2=(--http2 -k --resolve localhost:18443:127.0.0.1)
expect_ok detect-h1 detect "$(request detect-h1 "$http/api/detect")" 1.1
expect_ok blur-h1   blur   "$(request blur-h1 "$http/api/blur" -H "$regions")" 1.1
expect_ok detect-h2 detect "$(request detect-h2 "$https/api/detect" "${h2[@]}")" 2
expect_ok blur-h2   blur   "$(request blur-h2 "$https/api/blur" -H "$regions" "${h2[@]}")" 2

after=$(warnings)
temp_files=$("${compose[@]}" exec -T nginx sh -c 'find /var/cache/nginx -type f | wc -l' | tr -d ' ')
echo "nginx temp-file warnings for app routes: $((after - before)); files under /var/cache/nginx: $temp_files"
[ "$((after - before))" -eq 0 ] || fail "Nginx buffered app traffic to disk"

# Control: default-style buffering must hit the disk (otherwise the warning check proves nothing).
expect_ok control-detect detect "$(request control-detect "$http/__control/api/detect")"
expect_ok control-blur   blur   "$(request control-blur "$http/__control/api/blur" -H "$regions")"
control=$(( $(warnings) - after ))
echo "nginx temp-file warnings for the control route: $control"
[ "$control" -ge 1 ] || fail "control route did not buffer to disk — the check cannot detect regressions"

# Negative controls: the response checks must reject wrong answers.
read -r status _ <<<"$(request missing "$http/api/does-not-exist")"
[ "$status" = 404 ] || fail "expected 404 for a missing route, got $status"
( expect_ok missing detect "$status 1.1 x" ) >/dev/null 2>&1 && fail "a 404 was accepted as a detect result"
validate blur "$work/detect-h1" 2>/dev/null && fail "a JSON body was accepted as a blurred image"
validate detect "$work/blur-h1" 2>/dev/null && fail "an image body was accepted as detect JSON"
head -c 1000 "$work/blur-h1" > "$work/truncated"
validate blur "$work/truncated" 2>/dev/null && fail "a truncated image was accepted"
echo "negative controls: 404, swapped bodies and a truncated image are rejected"

app_id=$("${compose[@]}" ps -q app)
readonly_fs=$(docker inspect -f '{{.HostConfig.ReadonlyRootfs}}' "$app_id")
user=$("${compose[@]}" exec -T app id -u | tr -d '\r')
health=$(docker inspect -f '{{.State.Health.Status}}' "$app_id")
changes=$(docker diff "$app_id" | wc -l | tr -d ' ')
echo "app: read-only=$readonly_fs uid=$user health=$health filesystem-changes=$changes"
[ "$readonly_fs" = true ] && [ "$user" = 10001 ] && [ "$health" = healthy ] && [ "$changes" = 0 ] \
  || fail "app container hardening"

echo "PASS"
